### PR TITLE
feat: get eslint v9 to work

### PR DESCRIPTION
**Pull request by kristof-mattei**
# How? 

`eslint/use-at-your-own-risk` exposes `builtinRules`, which is the same (albeit updated) ruleset of ESLint.

Since we only need the names of the rules, and not the actual implementation, we're fine using this. [`eslint-plugin-unicorn`](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/891842d539d0d002119e9c476a050a12d3936a75/rules/utils/get-builtin-rule.js#L4) uses the same.

The changes below are the absolute minimum, to reduce diff & impact in migrating to `eslint-config-love@v64`.

# Plugin changes:

I replaced [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) by [`eslint-plugin-import-x`](https://github.com/un-ts/eslint-plugin-import-x), and subsequently renamed all `import/` prefixes to `import-x/`, as `eslint-plugin-import` doesn't support ESLint v9.

# Rule changes: 

* [`no-new-symbol`](https://eslint.org/docs/latest/rules/no-new-symbol) is deprecated, replaced by [`no-new-native-nonconstructor`](https://eslint.org/docs/latest/rules/no-new-native-nonconstructor).
* [`line-comment-position`](https://eslint.org/docs/latest/rules/line-comment-position), [`multiline-comment-style`](https://eslint.org/docs/latest/rules/multiline-comment-style) are no longer part of ESLint, and thus are no longer ignored as part of `_rules_to_consider.ts`.
* [`import-x/prefer-default-export`](https://github.com/un-ts/eslint-plugin-import-x/blob/HEAD/docs/rules/prefer-default-export.md) popped up as part of the [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) to [`eslint-plugin-import-x`](https://github.com/un-ts/eslint-plugin-import-x) migration. In order to minimize the migration cost, I've added it to `_rules_to_consider.ts` instead of enabling it.

### CODE REVIEW

**Comment by mightyiam** [comment]
I appreciate this, @kristof-mattei. Did you see discussion in #1734 ?

**Comment by kristof-mattei** [comment]
@mightyiam the link you posted refers to this PR.

**Comment by mightyiam** [comment]
Woops. Sorry. I meant #1589

**Comment by kristof-mattei** [comment]
> Woops. Sorry. I meant #1589

That's awesome. Let me revert the `import-x` changes and give that a shot.

**Comment by mightyiam** [comment]
I expect a PR from renovate that bumps eslint-plugin-import. But I don't see one. Is there really a new version?

**Comment by kristof-mattei** [comment]
> I expect a PR from renovate that bumps eslint-plugin-import. But I don't see one. Is there really a new version?

https://github.com/mightyiam/eslint-config-love/pull/1737

**Comment by kristof-mattei** [comment]
> I expect a PR from renovate that bumps eslint-plugin-import. But I don't see one. Is there really a new version?

Okay, not gonna work as `eslint-plugin-import` still restricts `eslint` to be max v8.

At the moment all we can do is switch to `eslint-plugin-import-x`.

**Pull request closed without merging**
